package com.kirandroid.stumate20.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF6750A4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFe8deff)
val md_theme_light_onPrimaryContainer = Color(0xFF22005D)
val md_theme_light_secondary = Color(0xa6c3c3c3)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF878787)
val md_theme_light_onSecondaryContainer = Color(0xFF1E192B)
val md_theme_light_tertiary = Color(0xFF7E5260)
val md_theme_light_onTertiary = Color(0xFF6750A4)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9E3)
val md_theme_light_onTertiaryContainer = Color(0xFF31101D)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF1C1B1E)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1C1B1E)
val md_theme_light_surfaceVariant = Color(0xFF505050)
val md_theme_light_onSurfaceVariant = Color(0xFF2f2f2f)
val md_theme_light_outline = Color(0xFF7A757F)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inversePrimary = Color(0xFFCFBCFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF6750A4)

val md_theme_dark_primary = Color(0xFFCFBCFF)
val md_theme_dark_onPrimary = Color(0xFF381E72)
val md_theme_dark_primaryContainer = Color(0xFF4F378A)
val md_theme_dark_onPrimaryContainer = Color(0xFFE9DDFF)
val md_theme_dark_secondary = Color(0xFFCBC2DB)
val md_theme_dark_onSecondary = Color(0xFF4A4061)
val md_theme_dark_secondaryContainer = Color(0xFF4A4458)
val md_theme_dark_onSecondaryContainer = Color(0xFFE8DEF8)
val md_theme_dark_tertiary = Color(0xFFEFB8C8)
val md_theme_dark_onTertiary = Color(0xFF4A2532)
val md_theme_dark_tertiaryContainer = Color(0xFF633B48)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9E3)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1C1B1E)
val md_theme_dark_onBackground = Color(0xFFE6E1E6)
val md_theme_dark_surface = Color(0xFF1C1B1E)
val md_theme_dark_onSurface = Color(0xFFE6E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF49454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4CF)
val md_theme_dark_outline = Color(0xFF948F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1E)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E6)
val md_theme_dark_inversePrimary = Color(0xFF6750A4)
val md_theme_dark_shadow = Color(0xFFFFFFFF)
val md_theme_dark_surfaceTint = Color(0xFFCFBCFF)

val md_theme_light_lightLightGray = Color(0xa6c3c3c3)

val textFieldHintColor = Color(0xFF5e5e5e)
val unfocusedAvatarColor = Color(0xFF838383)

val seed = Color(0xFF6750A4)
val primary = Color(0xFF6750A4)
val light_primary = Color(0xFF6750A4)
val light_onprimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFE9DDFF)
val light_onprimaryContainer = Color(0xFF22005D)
val dark_primary = Color(0xFFCFBCFF)
val dark_onprimary = Color(0xFF381E72)
val dark_primaryContainer = Color(0xFF4F378A)
val dark_onprimaryContainer = Color(0xFFE9DDFF)

val dividerDotsColor = Color(0xFF946750a4)
val dashboardBgColor = Color(0xFFFAFAFA)
val subjectCardBgColor = Color(0xFFe4F7FF)
val uploadYourFilesColor = Color(0xFFece5FF)

val txtSubjectsColor = Color(0xFF4d4d4d)
val txtStudNameColor = Color(0xFFD0BCFF)

val dashboardTopBgColor = Color(0xFFE0D2FF)
val txtBrowseYourSubs = Color(0xFFA7a0b8)

val classMatesCardBgColor = Color(0xFFfff7c7)
val classMatesBottomText = Color(0xFF4d4d4d)
val classMatesIconColor = Color(0xFFFFe6af)

// Navigation Bar
val navBarBgColor = Color(0xFFEBE4FF)
val navContentColor = Color(0xFF555555)
val navIndicatorColor = Color(0x7CC4BADF)

// Subject Dialog
val unfocusedDialogTextFieldColor = Color(0xFFDED0FF)